name: Publish release
on:
  workflow_dispatch:
  
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup dotnet tools
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build project
        run: dotnet build -c Release

      - name: Pack project
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release -o .

      - name: Push project
        run: dotnet nuget push **/*.nupkg -s ${{secrets.NUGET_FEED_URL}} -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
