name: Publish development
on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup dotnet tools
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build project
        run: dotnet build -c Release -p:VersionSuffix=development.$(date +%s)

      - name: Push project
        run: dotnet nuget push **/*.nupkg -s ${{secrets.GH_NUGET_FEED_URL}} -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate
