name: Publish preview
on:
  push:
    branches:
      - preview
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup dotnet tools
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build project
        run: dotnet build -c Release

      - name: Pack project
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --version-suffix "preview.$(date +%s)" --no-build -c Release -o .

      - name: Push project
        run: dotnet nuget push **/*.nupkg -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
